FROM node:18-bullseye

COPY os/02nocache /etc/apt/apt.conf.d/02nocache
COPY os/01_nodoc /etc/dpkg/dpkg.cfg.d/01_nodoc

WORKDIR /app

RUN npm install -g @ionic/cli

EXPOSE 8080

COPY scripts/ /usr/bin/
COPY docker /etc/thecore/docker
