version: "3.9"

services:
  frontend:
    networks:
      - webproxy

# This network is fixed to webproxy since is the name used in
# our production environments for the nginx-proxy docker image
# this way it can pickup the new rails app automatically and proxy it
# via http(s)
networks:
  webproxy:
    name: webproxy
    external: true
