version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      # - ..:/workspace:cached
      - ../:/workspaces/thecore_devcontainer:cached
      - ${HOME}/.docker/config.json:/home/vscode/.docker/config.json
      # - ../../dependencies:/workspaces/project/backend/vendor/dependencies:cached
      - /var/run/docker.sock:/var/run/docker.sock
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
